import { NAMESPACE_REDDIT } from '../../consts';

export const REQUEST_POSTS = `${NAMESPACE_REDDIT}/REQUEST_POSTS`;
export const RECEIVE_POSTS = `${NAMESPACE_REDDIT}/RECEIVE_POSTS`;
export const SELECT_REDDIT = `${NAMESPACE_REDDIT}/SELECT_REDDIT`;
export const INVALIDATE_REDDIT = `${NAMESPACE_REDDIT}/INVALIDATE_REDDIT`;
